### ISSUE TITLE
Font Missing

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/rfsom-box-gui#4]
I think there is a font missing in the installer script.  This is on the first rev PackRF boards.

root@analog:~# cat /var/log/rfsom-box-gui
Launcher json not found.
 jsonFileName  "font/dejavu-fonts-ttf-2.37/ttf/DejaVuSansMono.ttf"
sharedResPath  "/usr/local/bin/../share/rfsom-box-gui/"

**Comment by adisuciu** [comment]
Upon installing, the whole /share folder from the repository is deployed to /usr/local/share. It sounds like your build failed or something.

**Comment by adisuciu** [comment]
Turns out this line - https://github.com/analogdevicesinc/rfsom-box-gui/blob/master/tun_tap/Makefile#L15 should install the modem_filter.ftr to /usr/local/share/rfsom-box-gui . What happens in your case is that it copies the file modem_filter.ftr to /usr/local/share and changes it's file name to rfsom-box-gui . Eventually when the installer tries to copy the share folder to the /usr/local/share, it can't because there is already a file with the same name. 

Previously the folder /usr/local/share/rfsom-box-gui was created by another makefile. The commit fixes the issue by installing the rfsom-box-gui application first - https://github.com/analogdevicesinc/linux_image_ADI-scripts/commit/e20ec7406ac9bd162b40b718b71e3b789124f9c8

**Comment by tfcollins** [comment]
Thanks for the fixes 👍
